# SPDX-FileCopyrightText: 2024 Philip Molares
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "is-merlin"
SPDX-PackageSupplier = "Philip Molares"
SPDX-PackageDownloadLocation = "https://github.com/DerMolly/is-merlin"

[[annotations]]
path = ".idea/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Philip Molares"
SPDX-License-Identifier = "CC0-1.0"
